### ISSUE TITLE
Allow usage without vue-cli or vue.config.js

### ISSUE THREAD

**Issue by dschreij** [tjw-lint/jest-serializer-vue-tjw#67]
Great plugin, but I would recommend allowing the usage of this plugin without vue.config.js to make it applicable in broader contexts. I am integrating this plugin with nuxt, and it is hard to configure within that framework, because the plugin tries to find a physical vue.config.js file, which nuxt doesn't use. Maybe it would be a good idea to allow other ways of configuring this plugin. Of course, it is possible to just create an empty `vue.config.js` in the project root with the desired configuration to satisfy the plugin, but I'd say this is quite overkill (another config file!) and there seem to be more efficient approaches to me. Isn't it possible to directly pass options to the plugin in the `jest.config.js`?

**Comment by TheJaredWilcurt** [comment]
These are all good points!

The `vue.config.js` is only required if you want to customize the global settings for `jest-serializer-vue-tjw`. If the file does not exist then it just carries on and uses the default settings.

* https://github.com/tjw-lint/jest-serializer-vue-tjw/blob/master/src/loadOptions.js#L128

I've never used Nuxt. So I wasn't aware that they don't use the Vue-CLI config file. To avoid breaking changes, I'd like to keep the current `vue.config.js` support, but perhaps expanding to also work in a Jest config file or Nuxt config file would be good. It would require additional research into how these config files are designed and where best to place these options. Also there are a few different ways to name a jest config file, and the Jest settings can even live inside the `package.json` so it would take a decent amount of logic to resolve all of the places it could be. I'd prefer this all to be a series of automated checks. We then also need to decide priority. If the `jest-serializer-vue-tjw` settings are found in multiple locations, which one wins out? Are they combined? Do we alert that there is a duplicate and bail, or alert that there is a duplicate and carry on stating which version of the settings are being used?

For now though, it is a very easy work-around that you mentioned. When designing the API I knew there would be some that would build their own build system from scratch, outside of Vue-CLI, and those people would need to create a `vue.config.js` file just for this plugin if they wanted to change any of the defaults. But I figured that would be a small number of people. I didn't take into account Nuxt users.

Also I'm not sure how Vue 3 will effect the future of this plugin. It will likely require a complete re-write from scratch, slowly adding the same features back in (if possible). But if going to Vue 3 requires a lot of changes, then I think adopting the Jest config exclusively for settings would be the best approach.

**Comment by dschreij** [comment]
I am glad you like the suggestion! I guess this is something that many programs that allow multiple locations of configurations get confronted with. Eslint also allows configuration at several file locations, such as `.eslintrc` or `package.json`. Maybe we can mirror how they resolve the location of the final configuration file.

Regarding nuxt, it has a nuxt.config.js file, but I wouldn't place the configuration in there actually. In that case, package.json would be even better, or even config files/locations specific to Jest. My knowledge regarding this is very spotty too, so I have to look into this before I can really provide a useful suggestion regarding this.

**Comment by TheJaredWilcurt** [comment]
@dschreij 

Fixed in 3.19.0. You can now put a `"jestSerializer": {}` object in your `package.json` and it will use that and skip looking for `vue.config.js`.

**Comment by dschreij** [comment]
Great works. Thanks!
