### ISSUE TITLE
Failure on reading `vue.config.js`: cannot use import statement outside of module

### ISSUE THREAD

**Issue by ataias** [tjw-lint/jest-serializer-vue-tjw#79]
I am having issues using the serializer. In particular it seems to fail loading `vue.config.js`. The one I am using in a project is:

```js
require('@babel/register')({
  plugins: ['@babel/plugin-transform-modules-commonjs'],
  presets: ['@vue/cli-plugin-babel/preset']
})

module.exports = require('./vue.config.mjs').default
```

The referenced mjs is quite big and it contains some of the said imports:

```js
import { BundleAnalyzerPlugin } from 'webpack-bundle-analyzer'
import GitRevisionPlugin from 'git-revision-webpack-plugin'
import SentryWebpackPlugin from '@sentry/webpack-plugin'
import VuetifyLoaderPlugin from 'vuetify-loader/lib/plugin'
import path from 'path'

// ...
```

After setting up this serializer I get the following error:

```

    PrettyFormatPluginError: Cannot use import statement outside a module/Users/ataias/Projects/github.com/intellstartup/io.insure/vue.config.mjs:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import { APP_VERSION, BASE_URL, ENVIRONMENT, SENTRY_AUTH_TOKEN, SENTRY_GIT_REPO } from './src/core/config'
                                                                                             ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      4 | })
      5 |
    > 6 | module.exports = require('./vue.config.mjs').default
        |                  ^
      7 |

      at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:537:17)
      at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:579:25)
      at Object.<anonymous> (vue.config.js:6:18)
      at loadOptions (node_modules/jest-serializer-vue-tjw/src/loadOptions.js:137:17)
      at Object.print (node_modules/jest-serializer-vue-tjw/index.js:29:21)
```

Line 137 in `loadOptions` is exactly the following:

```js
  let vueConfig;
  if (fs.existsSync(vueConfigLocation)) {
    vueConfig = require(vueConfigLocation);
  }
```

--------
Not sure how to fix this issue exactly, but should the `vue.config.js` really be loaded? As you can see, some can be pretty complex and they are likely loaded in other places that do need it. If the file is loaded just for tjw specific fongis, maybe this serializer could use its own config like "tjw.config.js" or maybe have an option to specify an alternative `vue.config.js` that is crafted specifically for tjw?

**Comment by TheJaredWilcurt** [comment]
Related: #67

**Comment by TheJaredWilcurt** [comment]
@ataias

Fixed in 3.19.0. You can now put a `"jestSerializer": {}` object in your `package.json` and it will use that and skip looking for `vue.config.js`.

**Comment by BacLuc** [comment]
@TheJaredWilcurt 

do you plan to deprecate reading the config from vue.config.js, or support both ways for the foreseeable future?

**Comment by TheJaredWilcurt** [comment]
@BacLuc

* https://thejaredwilcurt.com/vue-snapshot-serializer

This is the new library that replaces `jest-serializer-vue-tjw` (will be deprecated *soon-ish*).

All settings are stored on `global`/`window`/`globalThis`. It makes it easier to set your default settings in the global `beforeEach`, and to tweak settings on a per-snapshot basis (see [Advanced Usage](https://thejaredwilcurt.com/vue-snapshot-serializer/#advanced)).

However it is Vue 3 only. So for Vue 2 projects, stick with `jest-serializer-vue-tjw` until you can transition to Vue 3.
